// Generated by CoffeeScript 1.11.1
(function() {
  app.config([
    '$locationProvider', '$routeProvider', function($locationProvider) {
      return $locationProvider.html5Mode(true);
    }
  ]);

}).call(this);

//# sourceMappingURL=config.js.map
