// Generated by CoffeeScript 1.11.1
(function() {
  app.config(function($routeProvider) {
    return $routeProvider.when('/', {
      templateUrl: '/simple_tips/app//view1/view1.html',
      controller: 'View1Ctrl as ctr'
    }).when('/simple_tips/app/', {
      templateUrl: '/simple_tips/app/view1/view1.html',
      controller: 'View1Ctrl as ctr'
    });
  });

}).call(this);

//# sourceMappingURL=routes.js.map
